import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Particles from '../components/Particles'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jordan Cardwell</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    
      <Particles />
      <Image src='head.png' width='26' height='35' />
    </div>
  )
}

export default Home
